#!/usr/bin/env zsh

alias ga="git add"
alias gap="git add -p"
alias gc="git commit"
alias gca="git commit --amend"
alias gco="git checkout"
alias gd="git difftool"
alias gnb="git checkout -b"
alias gps="git push"
alias gpsh="git push"
alias gs="git status"

alias :q="exit"
